# -*- coding: utf-8 -*-
"""code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHpkLK1s-0yklGypGs89pwuSp4fPUvSS
"""



!pip install transformers youtube-transcript-api

from transformers import pipeline
from youtube_transcript_api import YouTubeTranscriptApi

def fetch_transcript(video_id):
    transcript = YouTubeTranscriptApi.get_transcript(video_id)
    text = " ".join([entry['text'] for entry in transcript])
    return text

def summarize_text(text):
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
    # Split the text into smaller chunks if it's too long
    if len(text) > 1024: # This is for illustration change to an appropriate value
        chunks = [text[i:i + 1024] for i in range(0, len(text), 1024)]
        summary = ""
        for chunk in chunks:
            summary_chunk = summarizer(chunk, max_length=150, min_length=30, do_sample=False)
            summary += summary_chunk[0]['summary_text'] + " "
        return summary.strip()
    else:
        summary = summarizer(text, max_length=150, min_length=30, do_sample=False)
        return summary[0]['summary_text']

def summarize_youtube_video(video_id):
    transcript = fetch_transcript(video_id)
    summary = summarize_text(transcript)
    return summary

video_id = "GWj7-XEp87o"
summary = summarize_youtube_video(video_id)
print(summary)

