# -*- coding: utf-8 -*-
"""code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHpkLK1s-0yklGypGs89pwuSp4fPUvSS
"""

from transformers import pipeline, logging

# Suppress warnings
logging.set_verbosity_error()

# Load the sentiment analysis pipeline
classifier = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

def analyze_sentiment(text):
    """
    Performs sentiment analysis on a given text using a pre-trained model.

    Args:
        text: The text to analyze.

    Returns:
        A dictionary containing the sentiment label ("POSITIVE" or "NEGATIVE") and score.
        Returns an error message if analysis fails.

    """
    try:
        result = classifier(text)[0]
        return {"label": result['label'], "score": result['score']}
    except Exception as e:
        return f"Error during sentiment analysis: {e}"

# Example usage:
text = "This is a fantastic product! I highly recommend it."
sentiment = analyze_sentiment(text)
print(f"Sentiment: {sentiment}")

text2 = "I'm extremely disappointed with the service. It was terrible."
sentiment2 = analyze_sentiment(text2)
print(f"Sentiment: {sentiment2}")